version: "3.7"

networks:
  app-network:
    driver: bridge

services:
  db: 
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: 'noobts_db'
      MYSQL_USER: 'daniel.olivet'
      MYSQL_PASSWORD: 'Malaga1997//'
      MYSQL_ROOT_PASSWORD: 'Malaga1997//'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3308:3308'
    networks:
      - app-network
    expose:
      - '3308'
    volumes:
      - mysql-db:/var/lib/mysql
  noobts:
    depends_on:
      - db
    build: .
    ports:
      - 3000:3000
    networks:
      - app-network
    environment:
      - DB_PORT=3308
      - DB_HOST=db
      - DB_USERNAME=daniel.olivet
      - DB_PASSWORD=Malaga1997//
      - DB_NAME=noobts_db
    volumes:
      - noobts-app:/home/app
    command: npm start

volumes:
  mysql-db:
  noobts-app:
